eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769

spring:
  profiles:
    active: dev
  application:
    name: service-zuul
  cloud:
    gateway:
      routes:
        - id: programmer-util
          uri: lb://programmer-util
          predicates:
            - Path=/generator/**
          filters:
            - name: AuthFilter  # 身份认证
            - StripPrefix=1  #前缀，在当前路径匹配中表示去掉第一个前缀

        - id: programmer-blog
          uri: lb://programmer-blog
          predicates:
            - Path=/blog/**
          filters:
            - name: AuthFilter  # 身份认证
            - StripPrefix=1  #前缀，在当前路径匹配中表示去掉第一个前缀

      #以下为 跨域配置
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allow-credentials: true # 允许携带认证信息
            allowedOrigins: "*"    # 允许跨域的源(网站域名/ip)，设置*为全部
            allowedMethods: "*"   # 允许跨域的method， 默认为GET和OPTIONS，设置*为全部
            allowedHeaders: "*"   # 允许跨域请求里的head字段，设置*为全部