server:
  port: 8081
  tomcat:
    max-http-post-size: -1

spring:
  application:
    name: programmer-blog
  profiles:
    active: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/